### ISSUE TITLE
GitHub Actions - docker, docker-compose CI / CD

### ISSUE THREAD

**Issue by seunGit** [seunGit/TIL-TodayILearned#4]
# GitHub Actions - docker, docker-compose CI / CD

[***CI / CD***](https://seungit.github.io/posts/cicd/) 개념을 먼저 학습하자!

## AWS EC2 인스턴스 생성하기
먼저 AWS에서 EC2 인스턴스를 생성해야 한다.
생성과정은 간단하기 떄문에 [**여기**](https://velog.io/@kyj311/AWS-EC2%EC%95%8C%EC%95%84%EB%B3%B4%EA%B8%B0)를 참고해서 생성하면 좋을 것 같다. 여기에서는 `Ubuntu` 로 설치하였다.

## EC2 인스턴스 내 Docker 설치하기
EC2 내에 Docker와 Docker-Compose를 설치해야한다.
설치 과정은 [***도커 공식홈페이지***](https://docs.docker.com/engine/install/ubuntu/)에 따라 설치했다. 번역기 돌려서 확인하면 된다. 그대로 순서대로 진행하였다.

## GtitHub Actions 스크립트 생성

[`프로젝트`](https://github.com/Challenge-Hanbang-E/Hanbang-E) 진행시 ci 와 cd 파이프라인을 구분해서 yml파일을 생성하였다.

## Dockerfile 작성
```
FROM openjdk:17-alpine
ARG JAR_FILE=./build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```

## docker-compose.redis.yml 추가
ci 실행 시 `docker-compose.redis` 가 실행 되도록 추가하였다.
ci 과정에서 build되기 전에 redis image를 띄우는 작업이다.
이렇게 작성하지 않으니 ci 과정에서 계속 build가 실패하는 상황이 발생되었다.
ci test 과정에서 `contextLoads() FAILED` 오류 발생 (Redis가 실행이 되지 않아서 나는 오류로 판단함)

***ci-pipeline.yml***
```yml
# 도커 환경 init
      - name: Env Set Using Docker
        run: docker-compose -f docker-compose.redis.yml up -d

      # gradle 캐싱
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
```

## docker-compose.yml 파일과 docker-compose.redis.yml 분리 이유
`docker-compose.yml` 파일 내 `spring-boot`가 중복실행이 된다고 판단되어 구붓짓게 됨.<br><br>

***docker-compose.redis.yml***
```yml
version: "3.9"

services:
  redis_container:
    container_name: redis_boot
    image: redis:latest
    ports:
      - 6379:6379
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server
```
